import type { DiscoveryQuestion } from "../types";

/** Fuente: docs/discovery/REMISTAR-DISCOVERY-1-cuestionario-operativo.md §1, §21, §22. */
export const empresaQuestions: DiscoveryQuestion[] = [
  {
    id: "empresa-razon-social",
    sectionId: "empresa",
    order: 1,
    title: "Nombre de la empresa",
    prompt: "¿Cuál es la razón social y el nombre comercial exacto de Remistar?",
    tip: "El nombre legal y el nombre con el que se conoce a la empresa.",
    why: "Define cómo se presenta Remistar en el sistema, en documentos y en la facturación.",
    importance: "critico",
    type: "texto_corto",
    placeholder: "Ej: Remistar S.A. / Remistar",
  },
  {
    id: "empresa-cantidad-personas",
    sectionId: "empresa",
    order: 2,
    title: "Tamaño del equipo",
    prompt: "¿Cuántas personas trabajan hoy en Remistar en total?",
    tip: "Un número aproximado alcanza.",
    why: "Ayuda a dimensionar cuántos usuarios va a tener el sistema.",
    importance: "critico",
    type: "numero",
  },
  {
    id: "empresa-cantidad-vehiculos",
    sectionId: "empresa",
    order: 3,
    title: "Tamaño de la flota",
    prompt: "¿Cuántos vehículos componen la flota actualmente?",
    importance: "critico",
    type: "numero",
  },
  {
    id: "empresa-roles-equipo",
    sectionId: "empresa",
    order: 4,
    title: "Roles del equipo",
    prompt: "¿Qué roles existen hoy en el equipo de Remistar?",
    tip: "Marcá todos los que correspondan.",
    why: "Cada rol probablemente necesite una vista distinta del sistema.",
    importance: "critico",
    type: "multiple",
    allowOther: true,
    options: [
      { value: "chofer", label: "Chofer" },
      { value: "administrativo", label: "Administrativo" },
      { value: "mecanico", label: "Mecánico" },
      { value: "comercial", label: "Comercial" },
      { value: "gonzalo_dueno", label: "Gonzalo (dueño / coordinador general)" },
      { value: "socio", label: "Socio" },
    ],
  },
  {
    id: "empresa-horarios-operacion",
    sectionId: "empresa",
    order: 5,
    title: "Horarios de operación",
    prompt: "¿Qué horarios cubre la operación de Remistar?",
    importance: "critico",
    type: "unica",
    options: [
      { value: "24_7", label: "24 horas, todos los días" },
      { value: "horario_diurno", label: "Horario diurno" },
      { value: "horario_extendido", label: "Horario extendido (mañana a noche)" },
      { value: "variable_segun_demanda", label: "Variable según demanda" },
    ],
  },
  {
    id: "empresa-volumen-servicios",
    sectionId: "empresa",
    order: 6,
    title: "Volumen de servicios",
    prompt: "¿Cuántos servicios realiza Remistar aproximadamente por semana?",
    importance: "importante",
    type: "unica",
    options: [
      { value: "menos_10", label: "Menos de 10" },
      { value: "10_30", label: "Entre 10 y 30" },
      { value: "30_60", label: "Entre 30 y 60" },
      { value: "60_100", label: "Entre 60 y 100" },
      { value: "mas_100", label: "Más de 100" },
    ],
  },
  {
    id: "empresa-mapa-tareas",
    sectionId: "empresa",
    order: 7,
    title: "Qué hace Gonzalo hoy",
    prompt: "Para cada tarea: ¿la hace Gonzalo hoy?, ¿podría delegarse?, ¿nunca debería automatizarse sin su aprobación?",
    tip: "Pensá en el día a día real, no en el ideal.",
    why: "Es el insumo principal para decidir qué puede sugerir el sistema y qué debe seguir decidiendo Gonzalo.",
    importance: "critico",
    type: "matriz",
    affectsModules: ["Automatizaciones", "Configuración"],
    matrixRows: [
      { value: "cotizar", label: "Cotizar un servicio" },
      { value: "coordinar_agenda", label: "Coordinar la agenda" },
      { value: "asignar_chofer_vehiculo", label: "Asignar chofer y vehículo" },
      { value: "atender_clientes", label: "Atender consultas de clientes" },
      { value: "gestionar_pagos_liquidaciones", label: "Gestionar pagos y liquidaciones" },
      { value: "controlar_flota_mantenimiento", label: "Controlar flota y mantenimiento" },
      { value: "decidir_precios_excepciones", label: "Decidir precios o excepciones" },
    ],
    matrixCols: [
      { value: "lo_hace_gonzalo_hoy", label: "Lo hace Gonzalo hoy" },
      { value: "podria_delegarse", label: "Podría delegarse" },
      { value: "nunca_automatizar", label: "Nunca automatizar sin su aprobación" },
    ],
  },
  {
    id: "empresa-mayores-problemas",
    sectionId: "empresa",
    order: 8,
    title: "Mayores problemas actuales",
    prompt: "Ordená del 1 (el mayor problema) al 3 los problemas actuales de la operación.",
    importance: "critico",
    type: "ranking",
    options: [
      { value: "coordinar_agenda", label: "Coordinar la agenda" },
      { value: "cobrar_a_tiempo", label: "Cobrar a tiempo" },
      { value: "controlar_gastos_choferes", label: "Controlar gastos de choferes" },
      { value: "mantener_flota", label: "Mantener la flota en buen estado" },
      { value: "encontrar_clientes_nuevos", label: "Encontrar clientes nuevos" },
      { value: "comunicacion_con_choferes", label: "Comunicación con los choferes" },
    ],
  },
  {
    id: "empresa-delegacion-decisiones",
    sectionId: "empresa",
    order: 9,
    title: "Nivel de delegación deseado",
    prompt:
      "¿Gonzalo quiere seguir teniendo la última palabra en las decisiones críticas (asignaciones, cobros, liquidaciones), o busca delegarlas progresivamente?",
    why: "Define si el sistema debe limitarse a informar/alertar o puede llegar a ejecutar acciones con aprobación.",
    importance: "critico",
    type: "unica",
    affectsModules: ["Automatizaciones e inteligencia"],
    options: [
      { value: "gonzalo_todo", label: "Gonzalo decide todo por ahora" },
      { value: "delegar_progresivo", label: "Delegar progresivamente, con supervisión" },
      { value: "no_se", label: "Todavía no lo sabe" },
    ],
  },
  {
    id: "empresa-herramientas-actuales",
    sectionId: "empresa",
    order: 10,
    title: "Herramientas digitales actuales",
    prompt: "¿Qué herramientas digitales usa Remistar hoy en cualquier parte del proceso?",
    importance: "critico",
    type: "multiple",
    allowOther: true,
    options: [
      { value: "whatsapp", label: "WhatsApp" },
      { value: "excel", label: "Excel / planillas" },
      { value: "google_calendar", label: "Google Calendar" },
      { value: "papel_cuaderno", label: "Papel / cuaderno" },
      { value: "software_gestion", label: "Algún software de gestión" },
      { value: "sistema_facturacion", label: "Sistema de facturación" },
      { value: "redes_sociales", label: "Redes sociales" },
      { value: "ninguna", label: "Ninguna" },
    ],
  },
  {
    id: "empresa-sistema-no-reemplazable",
    sectionId: "empresa",
    order: 11,
    title: "Sistemas que no se pueden reemplazar",
    prompt: "¿Existe algún sistema que no se pueda reemplazar y con el que este proyecto deba integrarse sí o sí?",
    tip: "Ej. el sistema de facturación electrónica habilitado por DGI.",
    importance: "importante",
    type: "texto_corto",
  },
  {
    id: "empresa-usuarios-futuros",
    sectionId: "empresa",
    order: 12,
    title: "Usuarios del futuro sistema",
    prompt: "¿Quiénes usarían el sistema en el día a día, además de Gonzalo?",
    importance: "importante",
    type: "multiple",
    options: [
      { value: "choferes", label: "Choferes" },
      { value: "administrativo", label: "Un administrativo" },
      { value: "contador", label: "El contador" },
      { value: "socios", label: "Socios" },
      { value: "nadie_mas", label: "Nadie más por ahora" },
    ],
  },
];
