import type { DiscoveryQuestion } from "../types";

/** Fuente: docs/discovery/REMISTAR-DISCOVERY-1-cuestionario-operativo.md §2. */
export const serviciosQuestions: DiscoveryQuestion[] = [
  {
    id: "servicios-tipos-ofrecidos",
    sectionId: "servicios",
    order: 1,
    title: "Tipos de servicio ofrecidos",
    prompt: "¿Qué tipos de servicio ofrece Remistar hoy?",
    why: "Define el catálogo de servicios que va a mostrar la app.",
    importance: "critico",
    type: "multiple",
    allowOther: true,
    options: [
      { value: "aeropuerto", label: "Aeropuerto" },
      { value: "puerto", label: "Puerto" },
      { value: "corporativo", label: "Traslados corporativos" },
      { value: "particular", label: "Traslados particulares" },
      { value: "eventos", label: "Eventos" },
      { value: "interior", label: "Viajes al interior" },
      { value: "por_hora", label: "Viajes por hora" },
      { value: "larga_distancia", label: "Viajes de larga distancia" },
      { value: "recurrente", label: "Servicios recurrentes" },
      { value: "personal_empresas", label: "Traslado de personal de empresas" },
      { value: "hoteles", label: "Hoteles" },
      { value: "turismo", label: "Turismo" },
      { value: "adultos_mayores", label: "Adultos mayores" },
      { value: "pacientes", label: "Pacientes" },
      { value: "escolares", label: "Escolares" },
    ],
  },
  {
    id: "servicios-matriz-caracteristicas",
    sectionId: "servicios",
    order: 2,
    title: "Características de cada tipo de servicio",
    prompt: "Para los tipos de servicio que marcaste: ¿es frecuente, rentable, complejo de coordinar, o necesita vehículo especial?",
    importance: "importante",
    type: "matriz",
    matrixRows: [
      { value: "aeropuerto", label: "Aeropuerto" },
      { value: "corporativo", label: "Corporativo" },
      { value: "eventos", label: "Eventos" },
      { value: "interior", label: "Viajes al interior" },
      { value: "recurrente", label: "Servicios recurrentes" },
      { value: "turismo", label: "Turismo" },
    ],
    matrixCols: [
      { value: "frecuente", label: "Frecuente" },
      { value: "rentable", label: "Rentable" },
      { value: "complejo", label: "Complejo de coordinar" },
      { value: "requiere_vehiculo_especial", label: "Requiere vehículo especial" },
    ],
  },
  {
    id: "servicios-recurrentes-existen",
    sectionId: "servicios",
    order: 3,
    title: "Servicios recurrentes",
    prompt: "¿Existen servicios recurrentes o contratados (ej. traslados diarios a una empresa, colegio, etc.)?",
    importance: "critico",
    type: "si_no_nose",
    affectsModules: ["Agenda", "Servicios"],
  },
  {
    id: "servicios-recurrentes-detalle",
    sectionId: "servicios",
    order: 4,
    title: "Detalle de servicios recurrentes",
    prompt: "Listá los servicios recurrentes que existan hoy (cliente y frecuencia aproximada).",
    importance: "importante",
    type: "lista_dinamica",
    placeholder: "Ej: Empresa X — traslado de personal, lunes a viernes",
    dependsOn: { questionId: "servicios-recurrentes-existen", equalsAny: ["si"] },
  },
  {
    id: "servicios-rechazados",
    sectionId: "servicios",
    order: 5,
    title: "Servicios que no se realizan",
    prompt: "¿Hay servicios que Remistar rechaza o no realiza? ¿Por qué motivo?",
    importance: "complementario",
    type: "texto_corto",
  },
  {
    id: "servicios-zonas-cobertura",
    sectionId: "servicios",
    order: 6,
    title: "Zonas de cobertura",
    prompt: "¿Existen zonas geográficas de cobertura definidas o restringidas?",
    importance: "importante",
    type: "multiple",
    allowOther: true,
    options: [
      { value: "montevideo", label: "Montevideo" },
      { value: "canelones", label: "Canelones" },
      { value: "interior_cercano", label: "Interior cercano" },
      { value: "interior_lejano", label: "Interior lejano" },
      { value: "exterior_pais", label: "Exterior del país" },
      { value: "sin_restriccion", label: "Sin restricción definida" },
    ],
  },
  {
    id: "servicios-diferenciador-operativo",
    sectionId: "servicios",
    order: 7,
    title: "Qué diferencia a cada servicio",
    prompt:
      "Para los 2-3 servicios más frecuentes: ¿qué los diferencia operativamente (vehículo requerido, anticipación necesaria, tarifa, chofer habilitado)?",
    importance: "importante",
    type: "texto_largo",
  },
];
