import type { DiscoveryQuestion } from "../types";

/** Fuente: docs/discovery/REMISTAR-DISCOVERY-1-cuestionario-operativo.md §4 Consultas + §5 Cotización. */
export const consultasQuestions: DiscoveryQuestion[] = [
  {
    id: "consultas-canales-entrada",
    sectionId: "consultas",
    order: 1,
    title: "Canales de entrada",
    prompt: "¿Por qué canales llegan hoy las consultas de servicio?",
    importance: "critico",
    type: "multiple",
    allowOther: true,
    options: [
      { value: "llamada", label: "Llamada telefónica" },
      { value: "whatsapp", label: "WhatsApp" },
      { value: "correo", label: "Correo electrónico" },
      { value: "instagram", label: "Instagram" },
      { value: "facebook", label: "Facebook" },
      { value: "sitio_web", label: "Sitio web" },
      { value: "cliente_recurrente", label: "Cliente recurrente (directo)" },
      { value: "empresa", label: "Empresa" },
      { value: "hotel", label: "Hotel" },
      { value: "agencia", label: "Agencia" },
      { value: "referido", label: "Referido" },
    ],
  },
  {
    id: "consultas-canal-principal",
    sectionId: "consultas",
    order: 2,
    title: "Canal principal",
    prompt: "¿Por qué canal llega hoy la mayoría de las consultas?",
    importance: "importante",
    type: "unica",
    options: [
      { value: "llamada", label: "Llamada telefónica" },
      { value: "whatsapp", label: "WhatsApp" },
      { value: "sitio_web", label: "Sitio web" },
      { value: "referido", label: "Referido / boca a boca" },
    ],
  },
  {
    id: "consultas-horario-atencion",
    sectionId: "consultas",
    order: 3,
    title: "Horario de atención",
    prompt: "¿En qué horario se atienden hoy las consultas?",
    importance: "critico",
    type: "unica",
    options: [
      { value: "horario_comercial", label: "Horario comercial" },
      { value: "extendido", label: "Extendido (mañana a noche)" },
      { value: "24_7", label: "24 horas" },
      { value: "variable", label: "Variable, según quién esté disponible" },
    ],
  },
  {
    id: "consultas-info-minima",
    sectionId: "consultas",
    order: 4,
    title: "Información mínima para cotizar",
    prompt: "¿Qué información pide Gonzalo (o quien atienda) al recibir una consulta?",
    importance: "critico",
    type: "multiple",
    allowOther: true,
    options: [
      { value: "origen_destino", label: "Origen y destino" },
      { value: "fecha_hora", label: "Fecha y hora" },
      { value: "cantidad_pasajeros", label: "Cantidad de pasajeros" },
      { value: "tipo_servicio", label: "Tipo de servicio" },
      { value: "equipaje", label: "Equipaje" },
      { value: "datos_contacto", label: "Datos de contacto" },
      { value: "forma_pago", label: "Forma de pago" },
    ],
  },
  {
    id: "consultas-info-que-falta",
    sectionId: "consultas",
    order: 5,
    title: "Información que suele faltar",
    prompt: "¿Qué información suele faltar o hay que volver a pedir?",
    importance: "importante",
    type: "multiple",
    options: [
      { value: "origen_destino", label: "Origen y destino exactos" },
      { value: "fecha_hora", label: "Fecha y hora" },
      { value: "cantidad_pasajeros", label: "Cantidad de pasajeros" },
      { value: "datos_contacto", label: "Datos de contacto" },
      { value: "forma_pago", label: "Forma de pago" },
    ],
  },
  {
    id: "consultas-fuera-horario",
    sectionId: "consultas",
    order: 6,
    title: "Consultas fuera de horario",
    prompt: "¿Qué pasa con las consultas que llegan fuera de horario?",
    importance: "importante",
    type: "unica",
    options: [
      { value: "se_responden_igual", label: "Se responden igual, apenas se puede" },
      { value: "quedan_para_el_dia_siguiente", label: "Quedan para el día siguiente" },
      { value: "se_pierden", label: "Se pierden con frecuencia" },
    ],
  },
  {
    id: "consultas-como-cotiza",
    sectionId: "consultas",
    order: 7,
    title: "Cómo se calcula el precio",
    prompt: "¿Cómo se calcula el precio de un servicio?",
    importance: "critico",
    type: "multiple",
    options: [
      { value: "por_distancia", label: "Por distancia" },
      { value: "por_zona", label: "Por zona" },
      { value: "por_tiempo", label: "Por tiempo" },
      { value: "tarifa_fija", label: "Tarifa fija" },
      { value: "combinacion", label: "Combinación de varios criterios" },
    ],
  },
  {
    id: "consultas-tarifa-publicada",
    sectionId: "consultas",
    order: 8,
    title: "Tarifa publicada o caso a caso",
    prompt: "¿Existe una tarifa publicada/fija o todo se cotiza caso a caso?",
    importance: "critico",
    type: "si_no_nose",
  },
  {
    id: "consultas-como-confirma",
    sectionId: "consultas",
    order: 9,
    title: "Cómo queda confirmado un servicio",
    prompt: "Si el cliente acepta la cotización, ¿cómo queda 'confirmado' el servicio hoy?",
    importance: "critico",
    type: "unica",
    options: [
      { value: "mensaje_whatsapp", label: "Mensaje de WhatsApp" },
      { value: "verbal", label: "Confirmación verbal (llamada)" },
      { value: "anotado_en_agenda", label: "Se anota en la agenda" },
    ],
  },
  {
    id: "consultas-cambios-cancelaciones",
    sectionId: "consultas",
    order: 10,
    title: "Cambios y cancelaciones",
    prompt: "¿Qué pasa cuando el cliente cambia datos o cancela el servicio?",
    importance: "importante",
    type: "multiple",
    options: [
      { value: "se_reagenda_sin_costo", label: "Se reagenda sin costo" },
      { value: "aplica_penalidad", label: "Aplica una penalidad" },
      { value: "depende_del_caso", label: "Depende del caso" },
      { value: "no_hay_politica_definida", label: "No hay política definida hoy" },
    ],
  },
];
