import type { DiscoveryQuestion } from "../types";

/** Fuente: docs/discovery/REMISTAR-DISCOVERY-1-cuestionario-operativo.md §3. */
export const clientesQuestions: DiscoveryQuestion[] = [
  {
    id: "clientes-tipos-cliente",
    sectionId: "clientes",
    order: 1,
    title: "Tipos de cliente",
    prompt: "¿Qué tipos de cliente existen hoy?",
    tip: "En una empresa puede pedir el viaje una secretaria, viajar otra persona, pagar la empresa y recibir la factura un contacto administrativo diferente.",
    why: "Define si hace falta diferenciar solicitante, pasajero, pagador y contacto de facturación.",
    importance: "critico",
    type: "multiple",
    allowOther: true,
    affectsModules: ["Clientes", "Facturación", "Cobranza"],
    options: [
      { value: "particular", label: "Particular" },
      { value: "empresa", label: "Empresa" },
      { value: "hotel", label: "Hotel" },
      { value: "agencia", label: "Agencia" },
      { value: "evento", label: "Evento" },
      { value: "institucion", label: "Institución" },
      { value: "cliente_frecuente", label: "Cliente frecuente" },
    ],
  },
  {
    id: "clientes-roles-distintos",
    sectionId: "clientes",
    order: 2,
    title: "Solicitante, pasajero, pagador",
    prompt: "Dentro de un mismo servicio, ¿pueden ser personas distintas quien solicita, quien viaja, quien paga y quien recibe la factura?",
    importance: "critico",
    type: "unica",
    options: [
      { value: "siempre_la_misma_persona", label: "Casi siempre es la misma persona" },
      { value: "a_veces_distintas", label: "A veces son distintas" },
      { value: "frecuentemente_distintas", label: "Frecuentemente son distintas" },
    ],
  },
  {
    id: "clientes-cuenta-corriente",
    sectionId: "clientes",
    order: 3,
    title: "Cuenta corriente",
    prompt: "¿Existen clientes corporativos con cuenta corriente o facturación mensual?",
    importance: "critico",
    type: "si_no_nose",
  },
  {
    id: "clientes-datos-indispensables",
    sectionId: "clientes",
    order: 4,
    title: "Datos indispensables",
    prompt: "¿Qué datos son indispensables de un cliente o pasajero?",
    importance: "critico",
    type: "multiple",
    allowOther: true,
    options: [
      { value: "nombre", label: "Nombre" },
      { value: "telefono", label: "Teléfono" },
      { value: "email", label: "Email" },
      { value: "documento", label: "Documento" },
      { value: "empresa_asociada", label: "Empresa asociada" },
      { value: "direccion", label: "Dirección" },
      { value: "datos_fiscales", label: "Datos fiscales" },
    ],
  },
  {
    id: "clientes-como-se-registran-hoy",
    sectionId: "clientes",
    order: 5,
    title: "Cómo se registra un cliente hoy",
    prompt: "¿Cómo se identifica y registra hoy a un cliente nuevo?",
    importance: "critico",
    type: "unica",
    options: [
      { value: "no_se_registra_formalmente", label: "No se registra formalmente" },
      { value: "planilla_excel", label: "Planilla Excel" },
      { value: "cuaderno_papel", label: "Cuaderno / papel" },
      { value: "agenda_telefono", label: "Agenda del teléfono" },
    ],
  },
  {
    id: "clientes-prioritarios-o-problematicos",
    sectionId: "clientes",
    order: 6,
    title: "Clientes con trato especial",
    prompt: "¿Existen clientes VIP, prioritarios o problemáticos que requieren trato especial?",
    importance: "importante",
    type: "multiple",
    options: [
      { value: "vip_chofer_preferido", label: "VIP con chofer preferido" },
      { value: "vip_vehiculo_preferido", label: "VIP con vehículo preferido" },
      { value: "forma_pago_especial", label: "Forma de pago especial" },
      { value: "historial_de_problemas", label: "Historial de problemas / reclamos" },
      { value: "ninguno_por_ahora", label: "Ninguno identificado por ahora" },
    ],
  },
  {
    id: "clientes-condiciones-especiales",
    sectionId: "clientes",
    order: 7,
    title: "Condiciones especiales",
    prompt: "¿Hay condiciones especiales (tarifas, plazos, exclusividad) acordadas con algún cliente puntual?",
    importance: "complementario",
    type: "texto_largo",
  },
];
