import type { DiscoveryQuestion } from "../types";

/** Fuente: docs/discovery/REMISTAR-DISCOVERY-1-cuestionario-operativo.md §6. */
export const agendaQuestions: DiscoveryQuestion[] = [
  {
    id: "agenda-donde-registra",
    sectionId: "agenda",
    order: 1,
    title: "Dónde se registra la agenda",
    prompt: "¿Cómo se organiza hoy la agenda de servicios?",
    importance: "critico",
    type: "unica",
    allowOther: true,
    options: [
      { value: "papel", label: "Papel" },
      { value: "excel", label: "Excel" },
      { value: "whatsapp", label: "WhatsApp (mensajes)" },
      { value: "agenda_mental", label: "Agenda mental de Gonzalo" },
      { value: "otra_app", label: "Otra app" },
    ],
  },
  {
    id: "agenda-anticipacion-tipica",
    sectionId: "agenda",
    order: 2,
    title: "Anticipación típica",
    prompt: "¿Con cuánta anticipación suelen coordinarse los servicios?",
    importance: "importante",
    type: "unica",
    options: [
      { value: "mismo_dia", label: "El mismo día" },
      { value: "1_2_dias", label: "1 a 2 días antes" },
      { value: "con_una_semana", label: "Con una semana o más" },
      { value: "variable_mucho", label: "Varía mucho" },
    ],
  },
  {
    id: "agenda-info-minima-servicio",
    sectionId: "agenda",
    order: 3,
    title: "Información mínima de un servicio agendado",
    prompt: "¿Qué información mínima tiene que tener cada servicio agendado?",
    importance: "critico",
    type: "multiple",
    allowOther: true,
    options: [
      { value: "cliente", label: "Cliente" },
      { value: "pasajero", label: "Pasajero" },
      { value: "origen_destino", label: "Origen y destino" },
      { value: "fecha_hora", label: "Fecha y hora" },
      { value: "chofer_asignado", label: "Chofer asignado" },
      { value: "vehiculo_asignado", label: "Vehículo asignado" },
      { value: "precio", label: "Precio" },
      { value: "estado", label: "Estado" },
    ],
  },
  {
    id: "agenda-quien-puede-modificar",
    sectionId: "agenda",
    order: 4,
    title: "Quién puede modificar la agenda",
    prompt: "¿Quién puede modificar un servicio agendado?",
    importance: "critico",
    type: "unica",
    options: [
      { value: "solo_gonzalo", label: "Solo Gonzalo" },
      { value: "gonzalo_y_administrativo", label: "Gonzalo y un administrativo" },
      { value: "cualquiera_del_equipo", label: "Cualquiera del equipo" },
    ],
  },
  {
    id: "agenda-estados-utilizados",
    sectionId: "agenda",
    order: 5,
    title: "Estados que usa la agenda",
    prompt: "¿Qué estados utiliza hoy para un servicio agendado?",
    importance: "critico",
    type: "multiple",
    allowOther: true,
    options: [
      { value: "pendiente", label: "Pendiente" },
      { value: "confirmado", label: "Confirmado" },
      { value: "asignado", label: "Asignado" },
      { value: "en_curso", label: "En curso" },
      { value: "finalizado", label: "Finalizado" },
      { value: "cancelado", label: "Cancelado" },
    ],
  },
  {
    id: "agenda-deteccion-superposiciones",
    sectionId: "agenda",
    order: 6,
    title: "Detección de superposiciones",
    prompt: "¿Cómo se detecta hoy si dos servicios se superponen para el mismo chofer o vehículo?",
    importance: "importante",
    type: "unica",
    allowOther: true,
    options: [
      { value: "revision_manual", label: "Revisión manual de Gonzalo" },
      { value: "no_se_detecta_hoy", label: "No se detecta hoy" },
      { value: "herramienta_lo_avisa", label: "Alguna herramienta lo avisa" },
    ],
  },
  {
    id: "agenda-vistas-necesarias",
    sectionId: "agenda",
    order: 7,
    title: "Vistas necesarias",
    prompt: "¿Qué vistas de la agenda serían útiles?",
    importance: "importante",
    type: "multiple",
    options: [
      { value: "dia", label: "Día" },
      { value: "semana", label: "Semana" },
      { value: "mes", label: "Mes" },
      { value: "lista", label: "Lista" },
      { value: "por_chofer", label: "Por chofer" },
      { value: "por_vehiculo", label: "Por vehículo" },
      { value: "por_cliente", label: "Por cliente" },
      { value: "por_zona", label: "Por zona" },
      { value: "por_estado", label: "Por estado" },
    ],
  },
  {
    id: "agenda-margen-entre-servicios",
    sectionId: "agenda",
    order: 8,
    title: "Margen entre servicios",
    prompt: "¿Qué margen mínimo se intenta dejar entre dos servicios de un mismo chofer o vehículo?",
    importance: "importante",
    type: "unica",
    options: [
      { value: "sin_margen_definido", label: "Sin margen definido" },
      { value: "15_30_min", label: "15 a 30 minutos" },
      { value: "30_60_min", label: "30 a 60 minutos" },
      { value: "mas_de_1h", label: "Más de 1 hora" },
      { value: "depende_de_la_zona", label: "Depende de la zona / tipo de viaje" },
    ],
  },
  {
    id: "agenda-servicios-recurrentes-manejo",
    sectionId: "agenda",
    order: 9,
    title: "Manejo de servicios recurrentes",
    prompt: "¿Cómo se manejan hoy los servicios recurrentes en la agenda (se cargan uno por uno, se replican, etc.)?",
    importance: "complementario",
    type: "texto_corto",
  },
];
