import type { DiscoveryQuestion } from "../types";

/** Fuente: docs/discovery/REMISTAR-DISCOVERY-1-cuestionario-operativo.md §7 + vínculo/modalidad de §7bis. */
export const choferesQuestions: DiscoveryQuestion[] = [
  {
    id: "choferes-modalidad-vinculo",
    sectionId: "choferes",
    order: 1,
    title: "Modalidad de vínculo",
    prompt: "¿Qué modalidades de vínculo existen hoy con los choferes?",
    importance: "critico",
    type: "multiple",
    allowOther: true,
    options: [
      { value: "empleado_relacion_dependencia", label: "Empleado en relación de dependencia" },
      { value: "tercerizado_monotributista", label: "Tercerizado / monotributista" },
      { value: "freelance_ocasional", label: "Freelance ocasional" },
      { value: "dueno_vehiculo_propio", label: "Dueño de su propio vehículo" },
    ],
  },
  {
    id: "choferes-vehiculo-propiedad",
    sectionId: "choferes",
    order: 2,
    title: "Vehículo con el que trabaja el chofer",
    prompt: "¿Con qué vehículo trabaja habitualmente cada chofer?",
    why: "El vínculo con el vehículo cambia cómo se arma la liquidación y los reintegros.",
    importance: "critico",
    type: "unica",
    affectsModules: ["Liquidación de choferes", "Gastos y rendiciones"],
    options: [
      { value: "siempre_de_remistar", label: "Siempre un vehículo de Remistar" },
      { value: "siempre_propio", label: "Siempre su vehículo propio" },
      { value: "puede_ser_cualquiera", label: "Puede ser cualquiera de los dos" },
    ],
  },
  {
    id: "choferes-disponibilidad-se-define",
    sectionId: "choferes",
    order: 3,
    title: "Cómo se define la disponibilidad",
    prompt: "¿Cómo se determina la disponibilidad horaria de cada chofer?",
    importance: "critico",
    type: "unica",
    allowOther: true,
    options: [
      { value: "turnos_fijos", label: "Turnos fijos" },
      { value: "chofer_avisa_cada_dia", label: "El chofer avisa cada día" },
      { value: "siempre_disponible_salvo_aviso", label: "Se lo considera siempre disponible salvo aviso" },
    ],
  },
  {
    id: "choferes-especialidades",
    sectionId: "choferes",
    order: 4,
    title: "Especialidades",
    prompt: "¿Existen choferes especializados en algo puntual?",
    importance: "importante",
    type: "multiple",
    allowOther: true,
    options: [
      { value: "idiomas", label: "Idiomas" },
      { value: "protocolo_corporativo", label: "Protocolo corporativo" },
      { value: "adultos_mayores", label: "Adultos mayores" },
      { value: "pacientes", label: "Pacientes" },
      { value: "mascotas", label: "Mascotas" },
      { value: "ninguna_particular", label: "Ninguna en particular" },
    ],
  },
  {
    id: "choferes-aceptan-o-rechazan",
    sectionId: "choferes",
    order: 5,
    title: "Aceptación o rechazo de viajes",
    prompt: "¿Los choferes pueden aceptar o rechazar un viaje que se les asigna?",
    importance: "critico",
    type: "unica",
    options: [
      { value: "no_se_les_pregunta", label: "No se les pregunta, se les avisa" },
      { value: "pueden_rechazar_con_motivo", label: "Pueden rechazar, dando un motivo" },
      { value: "pueden_rechazar_libremente", label: "Pueden rechazar libremente" },
    ],
  },
  {
    id: "choferes-motivos-rechazo-validos",
    sectionId: "choferes",
    order: 6,
    title: "Motivos válidos de rechazo",
    prompt: "¿Qué motivos de rechazo se consideran válidos hoy?",
    importance: "importante",
    type: "condicional",
    dependsOn: {
      questionId: "choferes-aceptan-o-rechazan",
      equalsAny: ["pueden_rechazar_con_motivo", "pueden_rechazar_libremente"],
    },
    options: [
      { value: "descanso", label: "Necesita descanso" },
      { value: "distancia", label: "Distancia / zona" },
      { value: "tipo_de_cliente", label: "Tipo de cliente" },
      { value: "vehiculo_no_apto", label: "Vehículo no apto" },
    ],
  },
  {
    id: "choferes-ven-importe-total",
    sectionId: "choferes",
    order: 7,
    title: "Visibilidad del importe del viaje",
    prompt: "¿El chofer ve hoy el importe total que se le cobra al cliente por el viaje?",
    importance: "critico",
    type: "si_no_nose",
    affectsModules: ["Choferes", "Liquidación de choferes"],
    recommendationPreview:
      "Según las respuestas actuales, sugerimos que el chofer vea únicamente la información necesaria para ejecutar el servicio y su propia liquidación, evitando información comercial sensible.",
  },
  {
    id: "choferes-que-informacion-ven",
    sectionId: "choferes",
    order: 8,
    title: "Qué información ve el chofer",
    prompt: "Además del importe, ¿qué otra información ve o debería ver el chofer de un servicio asignado?",
    importance: "critico",
    type: "multiple",
    options: [
      { value: "datos_pasajero", label: "Datos del pasajero" },
      { value: "direccion_exacta", label: "Dirección exacta" },
      { value: "telefono_cliente", label: "Teléfono del cliente" },
      { value: "indicaciones_especiales", label: "Indicaciones especiales" },
      { value: "historial_del_cliente", label: "Historial del cliente" },
    ],
  },
  {
    id: "choferes-documentos-a-controlar",
    sectionId: "choferes",
    order: 9,
    title: "Documentos a controlar",
    prompt: "¿Qué documentos del chofer deben controlarse?",
    importance: "importante",
    type: "multiple",
    options: [
      { value: "libreta_profesional", label: "Libreta profesional" },
      { value: "antecedentes", label: "Antecedentes" },
      { value: "carne_salud", label: "Carné de salud" },
      { value: "licencia_conducir", label: "Licencia de conducir" },
      { value: "ninguno_formal", label: "Ninguno se controla formalmente hoy" },
    ],
  },
  {
    id: "choferes-atrasos-e-incidentes",
    sectionId: "choferes",
    order: 10,
    title: "Atrasos e incidentes",
    prompt: "¿Qué se hace hoy cuando un chofer llega tarde o tiene un incidente?",
    importance: "importante",
    type: "unica",
    allowOther: true,
    options: [
      { value: "aviso_informal_por_whatsapp", label: "Aviso informal por WhatsApp" },
      { value: "se_reasigna_el_servicio", label: "Se reasigna el servicio" },
      { value: "no_hay_protocolo_definido", label: "No hay protocolo definido" },
    ],
  },
  {
    id: "choferes-gps-notificaciones",
    sectionId: "choferes",
    order: 11,
    title: "GPS y notificaciones",
    prompt: "¿Los choferes necesitarían GPS o notificaciones del sistema?",
    importance: "complementario",
    type: "multiple",
    options: [
      { value: "gps_en_tiempo_real", label: "GPS en tiempo real" },
      { value: "notificaciones_nuevo_viaje", label: "Notificaciones de nuevo viaje" },
      { value: "recordatorios_documentacion", label: "Recordatorios de documentación" },
      { value: "ninguno_por_ahora", label: "Ninguno por ahora" },
    ],
  },
];
