import type { DiscoveryQuestion } from "../types";

/** Fuente: docs/discovery/REMISTAR-DISCOVERY-1-cuestionario-operativo.md §8. */
export const vehiculosQuestions: DiscoveryQuestion[] = [
  {
    id: "vehiculos-propiedad-flota",
    sectionId: "vehiculos",
    order: 1,
    title: "Propiedad de la flota",
    prompt: "¿Los vehículos son propiedad de la empresa, de los choferes, o mixto?",
    importance: "critico",
    type: "unica",
    options: [
      { value: "toda_propia", label: "Toda propia de Remistar" },
      { value: "toda_de_terceros", label: "Toda de los choferes" },
      { value: "mixta", label: "Mixta" },
    ],
  },
  {
    id: "vehiculos-categorias",
    sectionId: "vehiculos",
    order: 2,
    title: "Categorías de vehículo",
    prompt: "¿Qué categorías de vehículo existen hoy?",
    importance: "critico",
    type: "multiple",
    allowOther: true,
    options: [
      { value: "sedan_ejecutivo", label: "Sedán ejecutivo" },
      { value: "van", label: "Van" },
      { value: "suv", label: "SUV" },
      { value: "minibus", label: "Minibús" },
    ],
  },
  {
    id: "vehiculos-capacidad-equipamiento",
    sectionId: "vehiculos",
    order: 3,
    title: "Capacidad y equipamiento relevante",
    prompt: "¿Qué diferencias de capacidad o equipamiento importan al asignar un vehículo?",
    importance: "importante",
    type: "multiple",
    allowOther: true,
    options: [
      { value: "cantidad_pasajeros", label: "Cantidad de pasajeros" },
      { value: "espacio_equipaje", label: "Espacio de equipaje" },
      { value: "aire_acondicionado", label: "Aire acondicionado" },
      { value: "sillas_para_ninos", label: "Sillas para niños" },
      { value: "accesibilidad_silla_ruedas", label: "Accesibilidad para silla de ruedas" },
    ],
  },
  {
    id: "vehiculos-estados-usados",
    sectionId: "vehiculos",
    order: 4,
    title: "Estados de un vehículo",
    prompt: "¿Qué estados debería poder tener un vehículo?",
    why: "Define si un vehículo con un problema pendiente puede seguir asignándose.",
    importance: "critico",
    type: "multiple",
    allowOther: true,
    affectsModules: ["Vehículos", "Mantenimiento", "Documentación y obligaciones"],
    options: [
      { value: "disponible", label: "Disponible" },
      { value: "reservado", label: "Reservado" },
      { value: "en_servicio", label: "En servicio" },
      { value: "en_espera", label: "En espera" },
      { value: "en_mantenimiento", label: "En mantenimiento" },
      { value: "en_reparacion", label: "En reparación" },
      { value: "fuera_de_servicio", label: "Fuera de servicio" },
      { value: "documentacion_vencida", label: "Documentación vencida" },
      { value: "service_proximo", label: "Service próximo" },
      { value: "no_apto_viaje_largo", label: "No apto para viaje largo" },
    ],
  },
  {
    id: "vehiculos-como-se-sabe-disponibilidad",
    sectionId: "vehiculos",
    order: 5,
    title: "Cómo se sabe la disponibilidad",
    prompt: "¿Cómo se sabe hoy si un vehículo está disponible en este momento?",
    importance: "critico",
    type: "unica",
    allowOther: true,
    options: [
      { value: "memoria_de_gonzalo", label: "Memoria de Gonzalo" },
      { value: "planilla_excel", label: "Planilla Excel" },
      { value: "agenda_papel", label: "Agenda en papel" },
      { value: "no_hay_metodo_claro", label: "No hay un método claro hoy" },
    ],
  },
  {
    id: "vehiculos-vehiculo-habitual-por-chofer",
    sectionId: "vehiculos",
    order: 6,
    title: "Vehículo habitual por chofer",
    prompt: "¿Cada vehículo tiene un chofer habitual asignado?",
    importance: "importante",
    type: "si_no_nose",
  },
  {
    id: "vehiculos-cuando-no-asignar",
    sectionId: "vehiculos",
    order: 7,
    title: "Cuándo un vehículo no debe asignarse",
    prompt: "¿Cuándo un vehículo NO debería asignarse a un servicio, aunque esté libre?",
    importance: "critico",
    type: "multiple",
    options: [
      { value: "documentacion_vencida", label: "Documentación vencida" },
      { value: "service_vencido", label: "Service vencido" },
      { value: "danos_visibles", label: "Daños visibles" },
      { value: "no_apto_para_el_tipo_de_viaje", label: "No apto para ese tipo de viaje" },
      { value: "sin_restriccion_definida", label: "Hoy no hay una regla definida" },
    ],
  },
];
