import type { DiscoveryQuestion } from "../types";

/** Fuente: docs/discovery/REMISTAR-DISCOVERY-1-cuestionario-operativo.md §9. */
export const asignacionQuestions: DiscoveryQuestion[] = [
  {
    id: "asignacion-criterios-ranking",
    sectionId: "asignacion",
    order: 1,
    title: "Criterios de asignación",
    prompt: "Ordená del más importante al menos importante los criterios que más influyen al asignar un viaje.",
    why: "Es el insumo crítico para cualquier motor de sugerencia de chofer/vehículo — sin esto se corre el riesgo de inventar reglas.",
    importance: "critico",
    type: "ranking",
    affectsModules: ["Asignación", "Agenda"],
    options: [
      { value: "cercania", label: "Cercanía al punto de partida" },
      { value: "disponibilidad", label: "Disponibilidad" },
      { value: "tipo_vehiculo", label: "Tipo de vehículo adecuado" },
      { value: "conocimiento_cliente", label: "Conocimiento previo del cliente" },
      { value: "puntualidad_experiencia", label: "Puntualidad / experiencia del chofer" },
      { value: "descanso_del_chofer", label: "Descanso del chofer" },
      { value: "costo_rentabilidad", label: "Costo / rentabilidad" },
      { value: "preferencia_cliente", label: "Preferencia explícita del cliente" },
    ],
  },
  {
    id: "asignacion-como-confirma",
    sectionId: "asignacion",
    order: 2,
    title: "Cómo se confirma la asignación",
    prompt: "¿Cómo se confirma hoy la asignación, con el chofer y con el cliente?",
    importance: "critico",
    type: "multiple",
    options: [
      { value: "mensaje_al_chofer", label: "Mensaje al chofer" },
      { value: "llamada_al_chofer", label: "Llamada al chofer" },
      { value: "mensaje_al_cliente", label: "Mensaje al cliente" },
      { value: "no_hay_confirmacion_formal", label: "No hay confirmación formal hoy" },
    ],
  },
  {
    id: "asignacion-escenario-dos-choferes",
    sectionId: "asignacion",
    order: 3,
    title: "Escenario: dos choferes disponibles",
    prompt: "Hay dos choferes disponibles para el mismo horario. ¿Qué pesa más para elegir entre ellos?",
    importance: "importante",
    type: "escenario",
    scenario: {
      situation: "Dos choferes están libres para el mismo horario y ambos podrían tomar el viaje.",
      options: [
        { value: "el_mas_cercano", label: "El que está más cerca" },
        { value: "el_de_mejor_relacion_con_el_cliente", label: "El de mejor relación con el cliente" },
        { value: "el_que_menos_horas_lleva_trabajadas", label: "El que menos horas lleva trabajadas" },
        { value: "el_mas_experimentado", label: "El más experimentado" },
      ],
    },
  },
  {
    id: "asignacion-escenario-vehiculo-cercano-con-service",
    sectionId: "asignacion",
    order: 4,
    title: "Escenario: vehículo cercano con service próximo",
    prompt: "El vehículo más cercano tiene un service programado para mañana. ¿Se asigna igual?",
    importance: "critico",
    type: "escenario",
    scenario: {
      situation: "El vehículo más cercano al punto de partida tiene un service próximo (no vencido).",
      options: [
        { value: "si_el_service_no_es_urgente", label: "Sí, si el service no es urgente" },
        { value: "no_se_busca_otro_vehiculo", label: "No, se busca otro vehículo" },
        { value: "depende_del_tipo_de_viaje", label: "Depende del tipo de viaje" },
      ],
    },
  },
  {
    id: "asignacion-escenario-cliente-prefiere-chofer",
    sectionId: "asignacion",
    order: 5,
    title: "Escenario: cliente pide un chofer no disponible",
    prompt: "El cliente pide explícitamente un chofer que no está disponible en ese horario. ¿Qué se hace?",
    importance: "importante",
    type: "escenario",
    scenario: {
      situation: "Un cliente VIP pide expresamente un chofer que ya tiene otro servicio asignado en ese horario.",
      options: [
        { value: "se_avisa_y_se_ofrece_otro", label: "Se avisa que no está disponible y se ofrece otro" },
        { value: "se_reacomoda_la_agenda_si_es_posible", label: "Se reacomoda la agenda si es posible" },
        { value: "se_consulta_con_gonzalo_caso_a_caso", label: "Se consulta con Gonzalo caso a caso" },
      ],
    },
  },
  {
    id: "asignacion-escenario-conductor-muchas-horas",
    sectionId: "asignacion",
    order: 6,
    title: "Escenario: chofer con muchas horas trabajadas",
    prompt: "Un chofer ya lleva muchas horas trabajadas y es el único disponible para un viaje largo. ¿Qué se prioriza?",
    importance: "critico",
    type: "escenario",
    scenario: {
      situation: "Queda un viaje largo por cubrir y el único chofer libre ya trabajó muchas horas ese día.",
      options: [
        { value: "se_asigna_igual", label: "Se asigna igual" },
        { value: "se_busca_alternativa_aunque_tarde_mas", label: "Se busca una alternativa aunque tarde más" },
        { value: "se_evalua_caso_a_caso_sin_regla_fija", label: "Se evalúa caso a caso, sin regla fija hoy" },
      ],
    },
  },
  {
    id: "asignacion-idoneidad-cliente",
    sectionId: "asignacion",
    order: 7,
    title: "Idoneidad para un cliente",
    prompt: "¿Cómo se define hoy que un chofer es 'idóneo' para un cliente o servicio en particular?",
    importance: "importante",
    type: "texto_largo",
  },
];
