import type { DiscoveryQuestion } from "../types";

/** Fuente: docs/discovery/REMISTAR-DISCOVERY-1-cuestionario-operativo.md §10. */
export const ejecucionQuestions: DiscoveryQuestion[] = [
  {
    id: "ejecucion-estados-reales-usados",
    sectionId: "ejecucion",
    order: 1,
    title: "Estados de ejecución",
    prompt: "De esta lista preliminar de estados, ¿cuáles usa (o le haría falta usar) Remistar hoy?",
    tip: "Es una hipótesis de estados posibles, no una decisión tomada.",
    importance: "critico",
    type: "multiple",
    allowOther: true,
    options: [
      { value: "asignado", label: "Asignado" },
      { value: "pendiente_aceptar", label: "Pendiente de aceptar" },
      { value: "aceptado", label: "Aceptado" },
      { value: "en_camino", label: "En camino" },
      { value: "en_origen", label: "En origen" },
      { value: "pasajero_a_bordo", label: "Pasajero a bordo" },
      { value: "en_viaje", label: "En viaje" },
      { value: "finalizado", label: "Finalizado" },
      { value: "pendiente_rendicion", label: "Pendiente de rendición" },
      { value: "cerrado", label: "Cerrado" },
    ],
  },
  {
    id: "ejecucion-quien-puede-cambiar-estado",
    sectionId: "ejecucion",
    order: 2,
    title: "Quién cambia el estado",
    prompt: "¿Quién puede cambiar el estado de un servicio en ejecución?",
    importance: "critico",
    type: "unica",
    options: [
      { value: "solo_el_chofer", label: "Solo el chofer" },
      { value: "solo_gonzalo", label: "Solo Gonzalo" },
      { value: "chofer_y_gonzalo", label: "El chofer y Gonzalo" },
    ],
  },
  {
    id: "ejecucion-como-sabe-gonzalo-que-avanza",
    sectionId: "ejecucion",
    order: 3,
    title: "Cómo se entera Gonzalo del avance",
    prompt: "¿Cómo sabe Gonzalo hoy que un servicio salió, llegó o finalizó?",
    importance: "critico",
    type: "unica",
    allowOther: true,
    options: [
      { value: "mensaje_de_whatsapp", label: "Mensaje de WhatsApp del chofer" },
      { value: "llamada", label: "Llamada" },
      { value: "no_se_entera_en_tiempo_real", label: "No se entera en tiempo real" },
    ],
  },
  {
    id: "ejecucion-registra-kilometraje",
    sectionId: "ejecucion",
    order: 4,
    title: "Registro de kilometraje",
    prompt: "¿Se registra el kilometraje recorrido por servicio?",
    importance: "importante",
    type: "si_no_nose",
  },
  {
    id: "ejecucion-que-pasa-si-hay-espera",
    sectionId: "ejecucion",
    order: 5,
    title: "Esperas más largas de lo previsto",
    prompt: "¿Qué pasa si el chofer tiene que esperar más de lo previsto?",
    importance: "importante",
    type: "unica",
    options: [
      { value: "se_cobra_espera_adicional", label: "Se cobra una espera adicional" },
      { value: "se_absorbe_sin_cobrar", label: "Se absorbe sin cobrar" },
      { value: "depende_del_cliente", label: "Depende del cliente" },
      { value: "no_hay_politica", label: "No hay política definida hoy" },
    ],
  },
  {
    id: "ejecucion-pasajero-ausente",
    sectionId: "ejecucion",
    order: 6,
    title: "Pasajero que no aparece",
    prompt: "¿Qué pasa si el pasajero no aparece?",
    importance: "critico",
    type: "unica",
    options: [
      { value: "se_espera_un_tiempo_y_se_va", label: "Se espera un tiempo y el chofer se va" },
      { value: "se_cobra_igual", label: "Se cobra igual" },
      { value: "se_avisa_a_gonzalo_y_decide", label: "Se avisa a Gonzalo y él decide" },
      { value: "no_hay_protocolo", label: "No hay protocolo definido hoy" },
    ],
  },
  {
    id: "ejecucion-cuando-se-considera-finalizado",
    sectionId: "ejecucion",
    order: 7,
    title: "Cuándo se considera finalizado",
    prompt: "¿Cuándo se considera finalizado un servicio?",
    importance: "importante",
    type: "unica",
    allowOther: true,
    options: [
      { value: "cuando_el_pasajero_baja", label: "Cuando el pasajero baja" },
      { value: "cuando_el_chofer_avisa", label: "Cuando el chofer avisa" },
      { value: "cuando_se_cierra_administrativamente", label: "Cuando se cierra administrativamente" },
    ],
  },
];
