import type { DiscoveryQuestion } from "../types";

/** Fuente: docs/discovery/REMISTAR-DISCOVERY-1-cuestionario-operativo.md §11. */
export const imprevistosQuestions: DiscoveryQuestion[] = [
  {
    id: "imprevistos-tipos-frecuentes",
    sectionId: "imprevistos",
    order: 1,
    title: "Tipos de imprevistos frecuentes",
    prompt: "¿Qué tipo de imprevistos son más frecuentes?",
    importance: "critico",
    type: "multiple",
    allowOther: true,
    options: [
      { value: "atraso", label: "Atraso" },
      { value: "averia", label: "Avería" },
      { value: "accidente", label: "Accidente" },
      { value: "chofer_ausente", label: "Chofer ausente" },
      { value: "pasajero_ausente", label: "Pasajero ausente" },
      { value: "cambio_recorrido", label: "Cambio de recorrido" },
      { value: "cambio_horario", label: "Cambio de horario" },
      { value: "exceso_equipaje", label: "Exceso de equipaje" },
      { value: "pasajeros_adicionales", label: "Pasajeros adicionales" },
      { value: "problema_pago", label: "Problema de pago" },
      { value: "problema_cliente", label: "Problema con el cliente" },
      { value: "trafico", label: "Tráfico" },
      { value: "vuelo_demorado", label: "Vuelo demorado" },
      { value: "vehiculo_incorrecto", label: "Vehículo incorrecto" },
    ],
  },
  {
    id: "imprevistos-quien-decide",
    sectionId: "imprevistos",
    order: 2,
    title: "Quién decide ante un imprevisto",
    prompt: "Ante un imprevisto durante un servicio, ¿quién decide qué hacer?",
    importance: "critico",
    type: "unica",
    options: [
      { value: "siempre_gonzalo", label: "Siempre Gonzalo" },
      { value: "el_chofer_puede_decidir_algunas_cosas", label: "El chofer puede decidir algunas cosas" },
      { value: "depende_del_tipo_de_imprevisto", label: "Depende del tipo de imprevisto" },
    ],
  },
  {
    id: "imprevistos-quien-debe-ser-avisado",
    sectionId: "imprevistos",
    order: 3,
    title: "Quién debe ser avisado",
    prompt: "Ante un imprevisto, ¿quién debe ser avisado?",
    importance: "importante",
    type: "multiple",
    options: [
      { value: "gonzalo", label: "Gonzalo" },
      { value: "cliente", label: "El cliente" },
      { value: "administrativo", label: "Un administrativo" },
      { value: "nadie_mas", label: "Nadie más" },
    ],
  },
  {
    id: "imprevistos-cuando-se-reasigna",
    sectionId: "imprevistos",
    order: 4,
    title: "Cuándo se reasigna",
    prompt: "¿Cuándo se reasigna chofer o vehículo ante un imprevisto?",
    importance: "critico",
    type: "unica",
    options: [
      { value: "apenas_se_detecta", label: "Apenas se detecta el problema" },
      { value: "solo_si_es_indispensable", label: "Solo si es indispensable" },
      { value: "se_evalua_caso_a_caso", label: "Se evalúa caso a caso" },
    ],
  },
  {
    id: "imprevistos-compensacion-cliente",
    sectionId: "imprevistos",
    order: 5,
    title: "Compensación al cliente",
    prompt: "¿Existen políticas de compensación al cliente ante un imprevisto de Remistar?",
    importance: "importante",
    type: "unica",
    options: [
      { value: "si_hay_politica_definida", label: "Sí, hay una política definida" },
      { value: "se_evalua_caso_a_caso", label: "Se evalúa caso a caso" },
      { value: "no_se_compensa", label: "No se compensa" },
    ],
  },
  {
    id: "imprevistos-cuando-se-bloquea-vehiculo",
    sectionId: "imprevistos",
    order: 6,
    title: "Cuándo se bloquea un vehículo",
    prompt: "¿Ante qué imprevistos un vehículo debería quedar bloqueado hasta revisión?",
    importance: "importante",
    type: "multiple",
    options: [
      { value: "averia", label: "Avería" },
      { value: "accidente", label: "Accidente" },
      { value: "danos_visibles", label: "Daños visibles" },
      { value: "ninguno_se_bloquea_automaticamente", label: "Ninguno se bloquea automáticamente hoy" },
    ],
  },
];
