import type { DiscoveryQuestion } from "../types";

/** Fuente: docs/discovery/REMISTAR-DISCOVERY-1-cuestionario-operativo.md §14 Mantenimiento + §15 Talleres + §16 Garantías. */
export const mantenimientoQuestions: DiscoveryQuestion[] = [
  {
    id: "mantenimiento-criterio-control",
    sectionId: "mantenimiento",
    order: 1,
    title: "Criterio de control del mantenimiento",
    prompt: "¿Cómo se controla hoy cuándo un vehículo necesita un service?",
    importance: "critico",
    type: "multiple",
    affectsModules: ["Mantenimiento", "Vehículos"],
    options: [
      { value: "por_fecha", label: "Por fecha" },
      { value: "por_kilometraje", label: "Por kilometraje" },
      { value: "ambos", label: "Ambos" },
      { value: "sin_criterio_formal", label: "Sin criterio formal hoy" },
    ],
  },
  {
    id: "mantenimiento-quien-decide-taller",
    sectionId: "mantenimiento",
    order: 2,
    title: "Quién decide llevar al taller",
    prompt: "¿Quién decide cuándo llevar un vehículo al taller?",
    importance: "critico",
    type: "unica",
    options: [
      { value: "siempre_gonzalo", label: "Siempre Gonzalo" },
      { value: "el_chofer_puede_avisar_y_gonzalo_decide", label: "El chofer avisa y Gonzalo decide" },
      { value: "el_taller_avisa", label: "El taller avisa según su propio criterio" },
    ],
  },
  {
    id: "mantenimiento-tipos-habituales",
    sectionId: "mantenimiento",
    order: 3,
    title: "Tipos de mantenimiento habituales",
    prompt: "¿Qué tipos de mantenimiento se realizan habitualmente?",
    importance: "importante",
    type: "multiple",
    allowOther: true,
    options: [
      { value: "aceite", label: "Aceite" },
      { value: "filtros", label: "Filtros" },
      { value: "frenos", label: "Frenos" },
      { value: "neumaticos", label: "Neumáticos" },
      { value: "alineacion", label: "Alineación" },
      { value: "bateria", label: "Batería" },
      { value: "distribucion", label: "Distribución" },
      { value: "amortiguadores", label: "Amortiguadores" },
      { value: "aire_acondicionado", label: "Aire acondicionado" },
      { value: "chapa_pintura", label: "Chapa y pintura" },
      { value: "revision_general", label: "Revisión general" },
    ],
  },
  {
    id: "mantenimiento-talleres-fijos",
    sectionId: "mantenimiento",
    order: 4,
    title: "Talleres habituales",
    prompt: "¿Trabajan siempre con los mismos talleres o varían según el caso?",
    importance: "importante",
    type: "unica",
    options: [
      { value: "talleres_fijos", label: "Talleres fijos" },
      { value: "varian_segun_el_caso", label: "Varían según el caso" },
      { value: "mixto", label: "Mixto" },
    ],
  },
  {
    id: "mantenimiento-que-pasa-vehiculo-en-taller",
    sectionId: "mantenimiento",
    order: 5,
    title: "Vehículo en mantenimiento",
    prompt: "¿Qué pasa operativamente cuando un vehículo entra en mantenimiento?",
    importance: "critico",
    type: "unica",
    options: [
      { value: "se_reemplaza_por_otro", label: "Se reemplaza por otro vehículo" },
      { value: "se_reduce_la_flota_disponible", label: "Se reduce la flota disponible" },
      { value: "depende_de_la_urgencia", label: "Depende de la urgencia" },
    ],
  },
  {
    id: "mantenimiento-historial-por-vehiculo",
    sectionId: "mantenimiento",
    order: 6,
    title: "Historial de mantenimiento",
    prompt: "¿Existe hoy un historial de mantenimiento por vehículo?",
    importance: "importante",
    type: "si_no_nose",
  },
  {
    id: "mantenimiento-garantias",
    sectionId: "mantenimiento",
    order: 7,
    title: "Garantías de reparaciones",
    prompt: "¿Los repuestos o reparaciones suelen tener garantía controlada?",
    importance: "complementario",
    type: "si_no_nose",
  },
];
