import type { DiscoveryQuestion } from "../types";

/** Fuente: docs/discovery/REMISTAR-DISCOVERY-1-cuestionario-operativo.md §17. */
export const documentacionQuestions: DiscoveryQuestion[] = [
  {
    id: "documentacion-tipos-a-controlar",
    sectionId: "documentacion",
    order: 1,
    title: "Documentación a controlar",
    prompt: "¿Qué documentación tiene vencimiento y debe controlarse?",
    importance: "critico",
    type: "multiple",
    allowOther: true,
    options: [
      { value: "patente", label: "Patente / matrícula" },
      { value: "seguro", label: "Seguro" },
      { value: "inspeccion_tecnica", label: "Inspección técnica" },
      { value: "habilitacion_remise", label: "Habilitación como remise" },
      { value: "libreta_profesional_chofer", label: "Libreta profesional del chofer" },
      { value: "carne_salud_chofer", label: "Carné de salud del chofer" },
      { value: "antecedentes_chofer", label: "Antecedentes del chofer" },
      { value: "multas", label: "Multas" },
    ],
  },
  {
    id: "documentacion-bloquea-vehiculo",
    sectionId: "documentacion",
    order: 2,
    title: "¿Bloquea al vehículo?",
    prompt: "¿Un vehículo con documentación vencida debería quedar automáticamente no disponible?",
    importance: "critico",
    type: "si_no_nose",
    affectsModules: ["Vehículos", "Documentación y obligaciones"],
  },
  {
    id: "documentacion-bloquea-chofer",
    sectionId: "documentacion",
    order: 3,
    title: "¿Bloquea al chofer?",
    prompt: "¿Un chofer con documentación vencida (libreta, carné de salud) debería quedar automáticamente no disponible?",
    importance: "critico",
    type: "si_no_nose",
  },
  {
    id: "documentacion-anticipacion-aviso",
    sectionId: "documentacion",
    order: 4,
    title: "Anticipación del aviso",
    prompt: "¿Con cuánta anticipación conviene avisar antes de un vencimiento?",
    importance: "importante",
    type: "unica",
    options: [
      { value: "mas_de_30_dias", label: "Más de 30 días" },
      { value: "15_a_30_dias", label: "Entre 15 y 30 días" },
      { value: "menos_de_15_dias", label: "Menos de 15 días" },
      { value: "sin_criterio_hoy", label: "Sin criterio hoy" },
    ],
  },
  {
    id: "documentacion-donde-se-guarda-comprobante",
    sectionId: "documentacion",
    order: 5,
    title: "Dónde se guarda el comprobante",
    prompt: "¿Dónde se guarda hoy el comprobante de un trámite o pago de documentación?",
    importance: "importante",
    type: "unica",
    options: [
      { value: "no_se_guarda_hoy", label: "No se guarda hoy" },
      { value: "carpeta_fisica", label: "Carpeta física" },
      { value: "fotos_en_el_celular", label: "Fotos en el celular" },
      { value: "planilla_digital", label: "Planilla digital" },
    ],
  },
  {
    id: "documentacion-responsable-control",
    sectionId: "documentacion",
    order: 6,
    title: "Responsable del control",
    prompt: "¿Quién es responsable de controlar hoy que nada esté vencido?",
    importance: "critico",
    type: "unica",
    options: [
      { value: "gonzalo", label: "Gonzalo" },
      { value: "un_administrativo", label: "Un administrativo" },
      { value: "cada_chofer_su_documentacion", label: "Cada chofer controla la suya" },
      { value: "nadie_en_particular", label: "Nadie en particular" },
    ],
  },
  {
    id: "documentacion-proximo-vencimiento-conocido",
    sectionId: "documentacion",
    order: 7,
    title: "Próximo vencimiento conocido",
    prompt: "Si conocés alguna fecha de vencimiento próxima (seguro, inspección, habilitación), indicala.",
    importance: "complementario",
    type: "fecha",
  },
];
