import type { DiscoveryQuestion } from "../types";

/** Fuente: docs/discovery/REMISTAR-DISCOVERY-1-cuestionario-operativo.md §7bis (gastos/comprobantes/aprobación) + §18. */
export const gastosQuestions: DiscoveryQuestion[] = [
  {
    id: "gastos-matriz-tipos",
    sectionId: "gastos",
    order: 1,
    title: "Tipos de gasto de bolsillo del chofer",
    prompt:
      "Para cada tipo de gasto: ¿está permitido?, ¿requiere autorización previa?, ¿requiere comprobante?, ¿puede refacturarse al cliente?",
    tip: "Confirmá o corregí esta lista de hipótesis.",
    importance: "critico",
    type: "matriz",
    matrixRows: [
      { value: "peaje", label: "Peaje" },
      { value: "combustible", label: "Combustible" },
      { value: "parking", label: "Estacionamiento" },
      { value: "desayuno", label: "Desayuno" },
      { value: "almuerzo_cena", label: "Almuerzo / cena" },
      { value: "alojamiento", label: "Alojamiento" },
      { value: "lavado", label: "Lavado" },
      { value: "reparacion_menor", label: "Reparación menor" },
      { value: "compra_urgente", label: "Compra urgente" },
    ],
    matrixCols: [
      { value: "permitido", label: "Permitido" },
      { value: "requiere_autorizacion", label: "Requiere autorización" },
      { value: "requiere_comprobante", label: "Requiere comprobante" },
      { value: "puede_refacturarse", label: "Puede refacturarse" },
    ],
  },
  {
    id: "gastos-requiere-autorizacion-previa",
    sectionId: "gastos",
    order: 2,
    title: "Autorización previa",
    prompt: "¿Todos los gastos requieren autorización previa de Gonzalo, o el chofer puede gastar y después rendir cuentas?",
    importance: "critico",
    type: "si_no_nose",
    affectsModules: ["Gastos y rendiciones", "Liquidación de choferes"],
    recommendationPreview: "Si la respuesta es 'sí', el sistema debería registrar quién autorizó, cuándo y por qué.",
  },
  {
    id: "gastos-comprobante-obligatorio",
    sectionId: "gastos",
    order: 3,
    title: "Comprobante obligatorio",
    prompt: "¿Es obligatorio presentar comprobante para que se reconozca un gasto?",
    importance: "critico",
    type: "si_no_nose",
  },
  {
    id: "gastos-que-pasa-sin-comprobante",
    sectionId: "gastos",
    order: 4,
    title: "Gasto sin comprobante",
    prompt: "¿Qué se hace hoy cuando un chofer no tiene comprobante de un gasto?",
    importance: "importante",
    type: "unica",
    dependsOn: { questionId: "gastos-comprobante-obligatorio", equalsAny: ["si"] },
    options: [
      { value: "no_se_reconoce", label: "No se reconoce" },
      { value: "se_reconoce_con_justificacion", label: "Se reconoce con justificación" },
      { value: "se_evalua_caso_a_caso", label: "Se evalúa caso a caso" },
    ],
  },
  {
    id: "gastos-limite-monto-sin-autorizacion",
    sectionId: "gastos",
    order: 5,
    title: "Límite de monto",
    prompt: "¿Existe un monto límite a partir del cual un gasto necesita autorización previa?",
    importance: "importante",
    type: "moneda",
  },
  {
    id: "gastos-como-se-entregan-comprobantes",
    sectionId: "gastos",
    order: 6,
    title: "Cómo se entregan los comprobantes",
    prompt: "¿Cómo entrega hoy el chofer los comprobantes a Gonzalo?",
    importance: "importante",
    type: "unica",
    allowOther: true,
    options: [
      { value: "foto_por_whatsapp", label: "Foto por WhatsApp" },
      { value: "papel_fisico", label: "Papel físico" },
      { value: "no_hay_metodo_definido", label: "No hay método definido" },
    ],
  },
  {
    id: "gastos-quien-aprueba",
    sectionId: "gastos",
    order: 7,
    title: "Quién aprueba los gastos",
    prompt: "¿Quién revisa y aprueba hoy los gastos presentados por un chofer?",
    importance: "critico",
    type: "unica",
    options: [
      { value: "siempre_gonzalo", label: "Siempre Gonzalo" },
      { value: "un_administrativo", label: "Un administrativo" },
      { value: "no_hay_revision_formal", label: "No hay revisión formal hoy" },
    ],
  },
  {
    id: "gastos-como-se-reintegra",
    sectionId: "gastos",
    order: 8,
    title: "Cómo se reintegra el gasto",
    prompt: "¿Cómo se reintegra al chofer el dinero de un gasto aprobado?",
    importance: "critico",
    type: "unica",
    options: [
      { value: "junto_con_la_liquidacion", label: "Junto con la liquidación" },
      { value: "aparte_e_inmediato", label: "Aparte e inmediato" },
      { value: "depende_del_monto", label: "Depende del monto" },
    ],
  },
  {
    id: "gastos-criterio-refacturacion",
    sectionId: "gastos",
    order: 9,
    title: "Criterio de refacturación",
    prompt: "¿Cómo se decide si un gasto se refactura (cobra) al cliente?",
    importance: "importante",
    type: "texto_corto",
  },
];
