import type { DiscoveryQuestion } from "../types";

/** Fuente: docs/discovery/REMISTAR-DISCOVERY-1-cuestionario-operativo.md §7bis (pago, períodos, adelantos, pago final). */
export const liquidacionesQuestions: DiscoveryQuestion[] = [
  {
    id: "liquidacion-periodicidad",
    sectionId: "liquidaciones",
    order: 1,
    title: "Periodicidad de la liquidación",
    prompt: "¿Con qué periodicidad se liquida hoy a los choferes?",
    importance: "critico",
    type: "multiple",
    affectsModules: ["Liquidación de choferes"],
    options: [
      { value: "diaria", label: "Diaria" },
      { value: "semanal", label: "Semanal" },
      { value: "quincenal", label: "Quincenal" },
      { value: "mensual", label: "Mensual" },
      { value: "por_viaje", label: "Por viaje" },
      { value: "varia_por_chofer", label: "Varía según el chofer" },
    ],
  },
  {
    id: "liquidacion-criterio-pago",
    sectionId: "liquidaciones",
    order: 2,
    title: "Criterio de pago al chofer",
    prompt: "¿Cómo se calcula lo que le corresponde a un chofer por un servicio?",
    tip: "Fórmula conceptual preliminar: servicios realizados + gastos aprobados + ajustes a favor − adelantos − descuentos autorizados = saldo estimado.",
    why: "Esta fórmula es preliminar y deberá adaptarse a las reglas reales de Remistar.",
    importance: "critico",
    type: "multiple",
    options: [
      { value: "comision_porcentaje", label: "Comisión / porcentaje sobre lo cobrado" },
      { value: "jornal_fijo", label: "Jornal fijo por día o turno" },
      { value: "tarifa_fija_por_viaje", label: "Tarifa fija por viaje" },
      { value: "sueldo_mensual", label: "Sueldo mensual" },
      { value: "combinacion", label: "Combinación de varios criterios" },
    ],
  },
  {
    id: "liquidacion-mismo-criterio-todos",
    sectionId: "liquidaciones",
    order: 3,
    title: "¿Mismo criterio para todos?",
    prompt: "¿El criterio de pago es el mismo para todos los choferes, o varía según el chofer, vehículo o tipo de servicio?",
    importance: "importante",
    type: "si_no_nose",
  },
  {
    id: "liquidacion-adelantos-existen",
    sectionId: "liquidaciones",
    order: 4,
    title: "Adelantos",
    prompt: "¿Se entregan adelantos de dinero a los choferes?",
    importance: "critico",
    type: "si_no_nose",
  },
  {
    id: "liquidacion-como-se-descuenta-adelanto",
    sectionId: "liquidaciones",
    order: 5,
    title: "Cómo se descuenta un adelanto",
    prompt: "¿Cómo se registra un adelanto y cómo se descuenta después en la liquidación?",
    importance: "importante",
    type: "texto_corto",
    dependsOn: { questionId: "liquidacion-adelantos-existen", equalsAny: ["si"] },
  },
  {
    id: "liquidacion-choferes-confirmacion",
    sectionId: "liquidaciones",
    order: 6,
    title: "Confirmación del chofer",
    prompt: "¿Cómo confirma o revisa el chofer su liquidación?",
    importance: "critico",
    type: "multiple",
    options: [
      { value: "revisa_importe_por_viaje", label: "Revisa el importe de cada viaje" },
      { value: "revisa_solo_el_total", label: "Revisa solo el total" },
      { value: "no_revisa_nada", label: "No revisa nada" },
      { value: "firma_o_confirma_por_whatsapp", label: "Firma o confirma por WhatsApp" },
    ],
  },
  {
    id: "liquidacion-forma-de-pago",
    sectionId: "liquidaciones",
    order: 7,
    title: "Forma de pago final",
    prompt: "¿Cómo se le paga hoy al chofer el saldo de la liquidación?",
    importance: "critico",
    type: "unica",
    options: [
      { value: "efectivo", label: "Efectivo" },
      { value: "transferencia", label: "Transferencia" },
      { value: "mixto", label: "Mixto, según el caso" },
    ],
  },
  {
    id: "liquidacion-queda-comprobante",
    sectionId: "liquidaciones",
    order: 8,
    title: "Comprobante de pago",
    prompt: "¿Queda algún registro o comprobante de que el chofer recibió el pago?",
    importance: "importante",
    type: "si_no_nose",
  },
  {
    id: "liquidacion-reclamos-frecuentes",
    sectionId: "liquidaciones",
    order: 9,
    title: "Reclamos frecuentes",
    prompt: "¿Ha habido reclamos de choferes por diferencias en su liquidación?",
    importance: "complementario",
    type: "si_no_nose",
  },
];
