import type { DiscoverySection } from "./types";

/**
 * Las 20 secciones del relevamiento, ordenadas de lo más importante y operativo
 * a lo más estratégico, tal como fue definido para esta ronda de Discovery con
 * Gonzalo. Cada sección reorganiza y condensa el contenido ya relevado en
 * docs/discovery/REMISTAR-DISCOVERY-1-cuestionario-operativo.md (ver mapeo en
 * docs/discovery/REMISTAR-CUESTIONARIO-DIGITAL-V1.md).
 */
export const discoverySections: DiscoverySection[] = [
  {
    id: "empresa",
    slug: "empresa",
    order: 1,
    title: "La empresa hoy",
    subtitle: "Qué es Remistar, cómo funciona y quién decide",
    objective: "Entender qué es Remistar, cómo funciona y quién toma decisiones.",
    difficulty: "simple",
    estimatedMinutes: 10,
  },
  {
    id: "servicios",
    slug: "servicios",
    order: 2,
    title: "Tipos de servicio",
    subtitle: "Qué tipos de viaje debe soportar la app",
    objective: "Identificar qué tipos de viaje debe soportar la app.",
    difficulty: "simple",
    estimatedMinutes: 10,
  },
  {
    id: "consultas",
    slug: "consultas-y-reservas",
    order: 3,
    title: "Consultas y reservas",
    subtitle: "Cómo llegan las solicitudes y se transforman en viajes confirmados",
    objective: "Entender cómo llegan las solicitudes y cómo se transforman en viajes confirmados.",
    difficulty: "media",
    estimatedMinutes: 12,
  },
  {
    id: "clientes",
    slug: "clientes-y-pasajeros",
    order: 4,
    title: "Clientes y pasajeros",
    subtitle: "Quién solicita, quién viaja, quién paga y quién recibe la factura",
    objective: "Diferenciar quién solicita, quién viaja, quién paga y quién recibe la factura.",
    difficulty: "media",
    estimatedMinutes: 10,
  },
  {
    id: "agenda",
    slug: "agenda-y-coordinacion",
    order: 5,
    title: "Agenda y coordinación",
    subtitle: "Cómo se organiza hoy la agenda",
    objective: "Entender cómo se organiza hoy la agenda.",
    difficulty: "media",
    estimatedMinutes: 10,
  },
  {
    id: "choferes",
    slug: "choferes",
    order: 6,
    title: "Choferes",
    subtitle: "Cómo trabajan los choferes y qué necesitan ver",
    objective: "Definir cómo trabajan los choferes y qué necesitan ver.",
    difficulty: "media",
    estimatedMinutes: 12,
  },
  {
    id: "vehiculos",
    slug: "vehiculos",
    order: 7,
    title: "Vehículos",
    subtitle: "Estructura de la flota y disponibilidad real",
    objective: "Definir la estructura de la flota y la disponibilidad real.",
    difficulty: "simple",
    estimatedMinutes: 10,
  },
  {
    id: "asignacion",
    slug: "asignacion",
    order: 8,
    title: "Asignación de chofer y vehículo",
    subtitle: "El criterio real que utiliza Gonzalo",
    objective: "Capturar el criterio real que utiliza Gonzalo para asignar chofer y vehículo.",
    difficulty: "compleja",
    estimatedMinutes: 15,
  },
  {
    id: "ejecucion",
    slug: "ejecucion",
    order: 9,
    title: "Ejecución del servicio",
    subtitle: "Desde que el viaje se asigna hasta que finaliza",
    objective: "Definir qué debe ocurrir desde que el viaje se asigna hasta que finaliza.",
    difficulty: "media",
    estimatedMinutes: 10,
  },
  {
    id: "imprevistos",
    slug: "imprevistos",
    order: 10,
    title: "Imprevistos e incidencias",
    subtitle: "Cómo responde Remistar ante problemas",
    objective: "Documentar cómo responde Remistar ante problemas.",
    difficulty: "media",
    estimatedMinutes: 12,
  },
  {
    id: "mantenimiento",
    slug: "mantenimiento",
    order: 11,
    title: "Mantenimiento",
    subtitle: "Cómo se controla la salud de los vehículos",
    objective: "Entender cómo se controla la salud de los vehículos, talleres y garantías.",
    difficulty: "media",
    estimatedMinutes: 12,
  },
  {
    id: "documentacion",
    slug: "documentacion",
    order: 12,
    title: "Documentación y obligaciones",
    subtitle: "Vencimientos que pueden afectar la operación",
    objective: "Controlar vencimientos que pueden afectar la operación.",
    difficulty: "simple",
    estimatedMinutes: 10,
  },
  {
    id: "gastos",
    slug: "gastos-y-rendiciones",
    order: 13,
    title: "Gastos y rendiciones",
    subtitle: "Qué gastos puede pagar un chofer y cómo se revisan",
    objective: "Definir qué gastos puede pagar un chofer y cómo se revisan.",
    difficulty: "compleja",
    estimatedMinutes: 15,
  },
  {
    id: "liquidaciones",
    slug: "liquidacion-de-choferes",
    order: 14,
    title: "Liquidación de choferes",
    subtitle: "Cómo se calcula y paga a cada chofer",
    objective: "Definir cómo se calcula y paga a cada chofer.",
    difficulty: "compleja",
    estimatedMinutes: 15,
  },
  {
    id: "facturacion",
    slug: "facturacion",
    order: 15,
    title: "Facturación",
    subtitle: "Qué debe integrarse y qué información necesita Remistar",
    objective: "Entender qué debe integrarse y qué información necesita Remistar.",
    difficulty: "media",
    estimatedMinutes: 10,
  },
  {
    id: "cobranza",
    slug: "cobranza",
    order: 16,
    title: "Cobranza",
    subtitle: "Cómo se controla lo que los clientes deben",
    objective: "Entender cómo se controla lo que los clientes deben.",
    difficulty: "media",
    estimatedMinutes: 10,
  },
  {
    id: "oportunidades",
    slug: "crm-y-oportunidades",
    order: 17,
    title: "CRM y oportunidades",
    subtitle: "Cómo detectar y trabajar oportunidades comerciales",
    objective: "Definir cómo detectar y trabajar oportunidades comerciales.",
    difficulty: "simple",
    estimatedMinutes: 8,
  },
  {
    id: "calidad",
    slug: "encuestas-y-calidad",
    order: 18,
    title: "Encuestas y calidad",
    subtitle: "Cómo medir y mejorar el servicio",
    objective: "Definir cómo medir y mejorar el servicio.",
    difficulty: "simple",
    estimatedMinutes: 8,
  },
  {
    id: "reportes",
    slug: "reportes-e-indicadores",
    order: 19,
    title: "Reportes e indicadores",
    subtitle: "Qué necesita ver Gonzalo para decidir",
    objective: "Definir qué necesita ver Gonzalo para decidir.",
    difficulty: "simple",
    estimatedMinutes: 8,
  },
  {
    id: "automatizaciones",
    slug: "automatizaciones-e-inteligencia",
    order: 20,
    title: "Automatizaciones e inteligencia",
    subtitle: "Qué puede recomendar el sistema y qué debe aprobar Gonzalo",
    objective: "Definir qué puede recomendar el sistema y qué debe aprobar Gonzalo.",
    difficulty: "compleja",
    estimatedMinutes: 12,
  },
];

export function getSectionBySlug(slug: string): DiscoverySection | undefined {
  return discoverySections.find((section) => section.slug === slug);
}

export function getSectionById(id: string): DiscoverySection | undefined {
  return discoverySections.find((section) => section.id === id);
}
